# ==============================
# 📝 CONFIGURACIÓN GENERAL
# ==============================
spring.application.name=vegetariano
server.port=8080

# ==============================
# 🌐 CONEXIÓN A BASE DE DATOS LOCAL (HeidiSQL)
# ==============================
# Usamos localhost para forzar la conexión a tu PC
spring.datasource.url=jdbc:postgresql://localhost:5432/grupo02?sslmode=disable
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================
# 📦 CONFIGURACIÓN JPA / HIBERNATE
# ==============================
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==============================
# 🔐 SEGURIDAD JWT
# ==============================
jwt.secret=95fc8e994d67e99f91b18b606a8a2d89e477aa141c598063f0c034201790845c3cc53d6cdcd1393e09d260
