spring.application.name=vegetariano

# ==============================
# 📦 CONFIGURACIÓN JPA / HIBERNATE
# ==============================
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==============================
# 🌐 CONFIGURACIÓN DE BASE DE DATOS
# ==============================
spring.datasource.driver-class-name=org.postgresql.Driver

# 👉 Si Render define las variables, las usará (Conexión a la DB Remota)
# 👉 Si no, usará los valores locales (localhost) con SSL activado
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/grupo02?sslmode=disable}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:vegetariano_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345}

# ==============================
# ⚙️ PUERTO DEL SERVIDOR
# ==============================
# Render usa un puerto dinámico; si no lo encuentra, usa 8080
server.port=${PORT:8080}

# ==============================
# 🔐 TOKEN JWT
# ==============================
# Usa la variable JWT_SECRET en Render o el valor local en tu PC
jwt.secret=${JWT_SECRET:95fc8e994d67e99f91b18b606a8a2d89e477aa141c598063f0c034201790845c3cc53d6cdcd1393e09d260}
