spring.application.name=vegetariano

# 🌐 CONEXIÓN HÍBRIDA
# En tu PC: Usa MariaDB (Puerto 3306)
# En Render: Usa lo que diga la variable de entorno
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/grupo02?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345}

# 📦 JPA / HIBERNATE
# Dejamos que Spring elija el dialecto automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ⚙️ PUERTO Y SEGURIDAD
server.port=${PORT:8080}
jwt.secret=${JWT_SECRET:95fc8e994d67e99f91b18b606a8a2d89e477aa141c598063f0c034201790845c3cc53d6cdcd1393e09d260}
